language: node_js
services:
- rabbitmq
sudo: required
dist: trusty
env:
  global:
  - AMAZON_API_BUCKET=the-grid-img
  - AMAZON_API_REGION=us-west-2
  - secure: lkm/6WpxNLhqHol6hQ4mkcoezFfrHtcFcD4XeFpLXorQeoZJSQ3e7Jf90t+6TY53rAgsdplCUG1p4Cth6PD6P6fQWpCVIJ2o4dWn6TJLUXLizzGHo8H6pSZclwLWGToKN6Su2i6Ik9t//T0XGzGaKGI3kqrPo3ybCLMtGuQfYIc=
  - secure: sMuerVUrthvDgfNGnWcvE11kKtQUNw8/VvIVAYNiYXKIjhiHKVXOvdLNca3jh1WUE7FM4R9LglqJMhgYmS+MBqY2heYaRb7FUfEk0TzK54qnYkXlEvMwmIzWYShkqqv1hqNCuwfW1IgWcVYSMSeE6JoJx+sSaBXmpYWY8AJ4raM=
node_js:
- '4.2'
before_install:
- sudo apt-get update -qq
- sudo apt-get --assume-yes install libsdl1.2-dev libgif-dev libjson-glib-dev libglib2.0-dev libpango1.0-dev
before_script:
- psql -c 'create database imgflo_test;' -U postgres
- ./node_modules/.bin/knex migrate:latest
script:
- export IMGFLO_TESTS_PERFORMANCE=1
- export IMGFLO_BROKER_URL=amqp://localhost
- export IMGFLO_WORKER=subprocess
- export DATABASE_URL=postgres://postgres:@localhost/imgflo_test
- export POSTGRES_NOSSL=1
- make travis-deps
- make release RELOCATE_DEPS=true
before_deploy:
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
deploy:
  provider: heroku
  strategy: git
  app: imgflo
  on:
    repo: imgflo/imgflo-server
    all_branches: true
    tags: true
  api_key:
    secure: GCiWB7do2UuUzxGXkbg6gzJFHyj9JsHhuL7AtRZAA40u3peUa4BS1SeFlKiJM4Qzmzi1GLp7InmehJAatVyEHM34r8i41NRqpexr4/eVhiLI4tOP0g5mNoi1jM2TAbGuhBjIexpgvJnCaStdj6AZSV/lRWI/isF80KOH8zwxPcI=
