language: node_js
services:
- rabbitmq
node_js:
- '0.12'
before_install:
- sudo apt-get update -qq
- sudo apt-get install libjson-glib-dev libsdl1.2-dev libgif-dev gdb
script:
- export IMGFLO_TESTS_PERFORMANCE=1
- export IMGFLO_BROKER_URL=amqp://localhost
- make travis-deps
- make release RELOCATE_DEPS=true
before_deploy:
- if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
deploy:
  provider: heroku
  strategy: git
  app: imgflo
  on:
    repo: jonnor/imgflo-server
    all_branches: true
    tags: true
  api_key:
    secure: GCiWB7do2UuUzxGXkbg6gzJFHyj9JsHhuL7AtRZAA40u3peUa4BS1SeFlKiJM4Qzmzi1GLp7InmehJAatVyEHM34r8i41NRqpexr4/eVhiLI4tOP0g5mNoi1jM2TAbGuhBjIexpgvJnCaStdj6AZSV/lRWI/isF80KOH8zwxPcI=
